apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-grafana-{{ .Values.serviceSuffix }}
  labels:
    app: grafana
{{ include "yonecloud.labels" . | indent 4 }}
spec:
  ports:
    - port: 3000
  selector:
    app: grafana