apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-alertmanager-{{ .Values.serviceSuffix }}
  labels:
    app: alertmanager
{{ include "yonecloud.labels" . | indent 4 }}
spec:
  ports:
    - name: alertmanager
      port: 9093
    - name: alertmanager-plug
      port: 9098
  selector:
    app: alertmanager