apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-consul
  labels:
{{ include "yonecloud.labels" . | indent 4 }}
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: {{ .Values.consul.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8500
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 8500
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: data
              mountPath: /opt/consul/data
            - name: config
              mountPath: /opt/consul/config
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- else }}
        - name: data
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: consul-k8s-data
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        {{- end }}
        - name: config
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: consul-k8s-config
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Mi