apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-consul-{{ .Values.serviceSuffix }}
  labels:
    app: consul
{{ include "yonecloud.labels" . | indent 4 }}
spec:
  ports:
    - port: 8500
  selector:
    app: consul