apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-ctrmanager-{{ .Values.serviceSuffix }}
  labels:
    app: ctrmanager
{{ include "yonecloud.labels" . | indent 4 }}
spec:
  ports:
    - port: 9096
  selector:
    app: ctrmanager