apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-yonecloud
  labels:
{{ include "yonecloud.labels" . | indent 4 }}
    app: yonecloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yonecloud
  template:
    metadata:
      labels:
        app: yonecloud
    spec:
      serviceAccountName: config-reloader-sa
      initContainers:
        - name: copy-config
          image: {{ .Values.yonecloud.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["sh", "-c", "cp -f /yoneCloud/webserver/config-file/default.ini /yoneCloud/webserver/config;if [ ! -f /yoneCloud/webserver/config/monitor.yml ]; then cp -f /yoneCloud/webserver/config-file/monitor.yml /yoneCloud/webserver/config; fi"]
          volumeMounts:
            - name: config-file
              mountPath: /yoneCloud/webserver/config-file
            - name: config
              mountPath: /yoneCloud/webserver/config
        - name: wait-for-grafana
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Values.name }}-grafana-{{ .Values.serviceSuffix }} 3000; do echo waiting for grafana; sleep 2; done;']
      containers:
        - name: yonecloud
          image: {{ .Values.yonecloud.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: GRAFANA_URL
              value: http://{{ .Values.name }}-grafana-{{ .Values.serviceSuffix }}:3000
            - name: DATA_SOURCE_URL
              value: http://{{ .Values.name }}-prometheus-{{ .Values.serviceSuffix }}:9090
          volumeMounts:
            - name: config-file
              mountPath: /yoneCloud/webserver/config-file
            - name: config
              mountPath: /yoneCloud/webserver/config
            - name: media
              mountPath: /yoneCloud/webserver/media
        - name: config-reloader
          image: {{ .Values.reloader.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
             - "--namespace=yonecloud"
             - "--file-to-configmap=/yoneCloud/webserver/config/monitor.yml:yonecloud-config"
          volumeMounts:
            - name: config
              mountPath: /yoneCloud/webserver/config
      volumes:
        - name: config
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: yonecloud-k8s-config
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Mi
        - name: media
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: yonecloud-k8s-media
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        - name: config-file
          configMap:
            name: yonecloud-config
            items:
              - key: "default.ini"
                path: "default.ini"
              - key: "monitor.yml"
                path: "monitor.yml"