kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  labels:
{{ include "yonecloud.labels" . | indent 4 }}
    app: redis
data:
  redis.conf: |-
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data

    stop-writes-on-bgsave-error yes
    rdbcompression yes

    bind 0.0.0.0
    protected-mode yes
    port 6379

    tcp-backlog 511
    timeout 0

    tcp-keepalive 300
    daemonize no

    appendonly no
    appendfilename "appendonly.aof"

    pidfile /data/redis.pid