apiVersion: v1
kind: Service
metadata:
  # name: {{ template "yonecloud.redis" . }} # mytest-yone-redis
  name: {{ .Values.name }}-redis-{{ .Values.serviceSuffix }}
  labels:
    app: redis
{{ include "yonecloud.labels" . | indent 4 }}
spec:
  ports:
    - port: 6379
  selector:
    app: redis