apiVersion: v1
data:
  SECRET_KEY: {{ template "yonecloud.mysql.encryptedSecretKey" . }}
kind: Secret
metadata:
  name: {{ .Values.name }}-secret-key
  labels:
{{ include "yonecloud.labels" . | indent 4 }}